### ISSUE TITLE
README

### ISSUE THREAD

**Issue by nathmo** [esseivan/ModuleBattery18650#1]
tu arrive a mettre le PDF du schema et un screenshot du rendu 3D de la board dans le README ? ^^

**Comment by esseivan** [comment]
yep ^^ je fais ca

**Comment by esseivan** [comment]
comme j'ai pris un mosfet avec Rds plus petit, j'ai du changer le footprint et j'ai pas encore adapté le pcb

**Comment by nathmo** [comment]
meme si c'est pas exacte c'est juste avoir une idée de la bete. ça pourrais servir dans d'autre design
